
#' ---
#' title: "pipeline of allele-specific RNAseq analysis of  C57BL_6NJ & PWK_PhJ mice."
#' author: "LiTingting(ting67@126.com)"
#' output:
#'   html_document:
#'     number_sections: false
#'     highlight: pygments
#'     theme: cerulean
#'     toc: yes
#' ---


setwd('~/cluster_home/project/liverCancer/results/rnaseq/f1_mouse/bygroup/f1_mice_all_mm39_rmDup/fetch_chrX_transcripts/')
knitr::opts_knit$set(root.dir = '~/cluster_home/project/liverCancer/results/rnaseq/f1_mouse/bygroup/f1_mice_all_mm39_rmDup/fetch_chrX_transcripts/')


#-----------------------------------------------------------------------------#
#
# 1. get the SNPs info of C57BL_6NJ & PWK_PhJ.  
#
# 2. generate allele-specif genome of C57BL_6NJ & PWK_PhJ.
#     the genome.fa files were generated by `gatk FastaAlternateReferenceMaker`,
#   but the chrnames were changed.
#
#    so the following scripts was for:
#       1. rename the chr-names back
#       2. check the SNP sites.
#
# 3. get gene_seq.fa from two allele-specific genomes.
# 4. generate blastdb for these sequence 
#
#
# 5. map fq.gz to mm39
# 6. fetch reads mapped to chrX
# 7. blast these reads against gene_seq.fa
# 8. check the blast results.
#
#
#
#
#
#-----------------------------------------------------------------------------#

suppressPackageStartupMessages(library(Biostrings))
suppressPackageStartupMessages(library(magrittr))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(GenomicFeatures))

library(GenomicRanges)
library(VariantAnnotation)
#library(TxDb.Mmusculus.UCSC.mm39.refGene)

#genes(TxDb.Mmusculus.UCSC.mm39.refGene)
#transcripts(TxDb.Mmusculus.UCSC.mm39.refGene)


#chrX_trans_meta <- read_tsv('~/cluster_home/ref/GENCODE/mm39_vM33/fetched_info/transcripts_gencode_clean.txt')
#chrX_trans_meta %<>% filter(seqname == 'chrX')
#chrX_trans_meta$gene_type %>% table()
#chrX_trans_meta <- chrX_trans_meta[chrX_trans_meta$gene_type %in% c('lncRNA', 'protein_coding'), ]


#-------------------------------------------------------------------------------



#' ### 1. generate transcprit.fa for each sample  
#' 
#' 
sam_files <- list.files('./sam', pattern = '*.txt', full.names = T)

sample_vec <- basename(sam_files) %>% gsub('.bam.txt', '', .)

cmd = paste0('mkdir ./split_fa/', sample_vec)
for (i in cmd) {
  system(i)
}



tmp <- read_tsv(sam_files[1], col_names = F)

tmp_list <- split(tmp, tmp$X3)
length(tmp_list)
tmp_list$ENSMUST00000000365.3

output_trans_fa <- function(transcript, sample_list){
  
  tmp <- sample_list[[transcript]]
  dsl <- DNAStringSet(tmp$X10)
  names(dsl) <- paste0(tmp$X1, '_', 1:length(tmp$X10))
  return(dsl)
}
output_trans_fa(transcript = 'ENSMUST00000000365.3', sample_list = tmp_list )
output_trans_fa(transcript = 'ENSMUST00000001155.11', sample_list = tmp_list )


total_dsl <- list()
for (i in 1:length(sam_files)) {
  print(i)
  tmp <- read_tsv(sam_files[i], col_names = F)
  tmp_list <- split(tmp, tmp$X3)
  length(tmp_list)
  tmp2 <- parallel::mclapply(names(tmp_list), output_trans_fa, sample_list = tmp_list, mc.cores = 72)
  names(tmp2) <- names(tmp_list)
  
  total_dsl[[i]] <- tmp2
}

total_dsl

length(total_dsl)


names(total_dsl) <- basename(sam_files) %>% paste0('sample_', .) %>% 
                    gsub('-', '_', .) %>% gsub('_chrX.bam.txt', '',. )

total_dsl$sample_1_F1_F_6W_CCl4_1$ENSMUST00000000365.3


# output fa files:   

lapply(total_dsl, length)

names(total_dsl$sample_1_F1_F_6W_CCl4_1$ENSMUST00000000365.3)


output_fa <- function(transcripts, list_dss){
  
  tmp <- list_dss[[transcripts]]
  
  writeXStringSet(tmp_dsl, paste0('./split_fa/', ))
  
  
}


for (i in names(total_dsl) ) {
  print(i)
  cmd = paste0('mkdir ./split_fa/', i)
  system(cmd)
  
  tmp <- total_dsl[[i]]
  
  mclapply(names(tmp), function(x){
    writeXStringSet(tmp[[x]], filepath = paste0('./split_fa/', i, '/', x, '.fa'))
  }, mc.cores = 76)
  
}



#' ### 2. generate bowtie2 index for each gene:  
#' 


chrX_genes <- readDNAStringSet('~/cluster_home/project//liverCancer/scripts/mouse_F1/RNA_seq/meta/blast/chrX_geneSeqs_mm39_C57BL_6NJ-PWK_PhJ.fa')


for (i in 1:1135) {
  tmp <- chrX_genes[c(i,1135 +i)]
  genename <- names(tmp)[1] %>% gsub('_C57BL_6NJ', '', .)
  print(genename)
  writeXStringSet(tmp, paste0('~/cluster_home/project/liverCancer/ref/ind-bwt2/mm39_genes/', genename, '_C57_PWK.fa'))
  
}




#' ### 3. generate bowtie2 index:  
#' 

fa_files <- list.files('~/cluster_home/project/liverCancer/ref/ind-bwt2/mm39_genes/', '*.fa', full.names = T)



sink('~/cluster_home/project/liverCancer/scripts/mouse_F1/RNA_seq/src/xargs_bt2.txt')

for (i in fa_files) {
  cmd <- sprintf("bowtie2-build %s %s \n", i, gsub('.fa$', '', i))
  cat(cmd)
}

sink()


#' ### 4. bowtie2 alignment  
#' 

getwd()
fa_files_perTrans <- list.files('~/cluster_home/project/liverCancer/results/rnaseq/f1_mouse/bygroup/f1_mice_all_mm39_rmDup/fetch_chrX_transcripts/split_fa', pattern = "*.fa", recursive = T, full.names = T)

head(fa_files_perTrans)


merged_df <- tibble(fa_files = fa_files_perTrans)


merged_df$sample <- dirname(merged_df$fa_files) %>% basename()
merged_df$transcript <- basename(merged_df$fa_files) %>% gsub('.fa$', '', .)


trans_meta <- read_tsv('~/cluster_home/ref/GENCODE/mm39_vM33/fetched_info/transcripts_gencode_clean.txt')

table(merged_df$transcript %in% trans_meta$transcript_id)


merged_df <- left_join(merged_df, trans_meta, by =join_by(transcript == transcript_id))


merged_df$gene_bt2idx <- paste0('/home/littt/project/liverCancer/ref/ind-bwt2/mm39_genes/', merged_df$gene_name, '_C57_PWK')
merged_df$gene_bt2idx



#' ### 4. bowtie2 alignment  
#' 

bt2_out_path="/home/littt/cluster_home/project/liverCancer/results/rnaseq/f1_mouse/bygroup/f1_mice_all_mm39_rmDup/fetch_chrX_transcripts/bowtie2"

sample_vec <- unique(merged_df$sample)
sink('~/cluster_home/project/liverCancer/scripts/mouse_F1/RNA_seq/src/xargs_bt2_align.txt')

for (i in sample_vec) {
  
  bt2_out <- paste0(bt2_out_path, '/', i)
  system(paste0('mkdir -p ', bt2_out))
  
  tmp_merged_df <- filter(merged_df, sample == i)
  
  gene_vec <- unique(tmp_merged_df$gene_name)
  
  for (j in gene_vec) {
    
    gene_merged_df <- filter(tmp_merged_df, gene_name == j)
    
    cmd = sprintf('bowtie2 -x %s --very-sensitive -f %s -S %s/%s.sam \n',
                  gene_merged_df$gene_bt2idx[1],
                  paste0(gene_merged_df$fa_files, collapse = ','),
                  bt2_out,
                  j)
    
    cat(cmd)
  }
  
  
}
sink()



unique(merged_df$gene_name)


grep('ENSMUSG', merged_df$gene_name, value = T)





#' ### 5. stats  
#' 

stat_files <- list.files("/home/littt/cluster_home/project/liverCancer/results/rnaseq/f1_mouse/bygroup/f1_mice_all_mm39_rmDup/fetch_chrX_transcripts/bowtie2/", 
                         pattern = 'stat.txt', recursive = T, full.names = T)


tes <- read.table(stat_files[1]) %>% as_tibble()


tes2 <- tes$V2 %>% gsub('_[PC].*$', '', .)


tes$gene_name <- tes$V2 %>% gsub('_[PC].*$', '', .)

tes

tes[grepl('C57', tes$V2), ]

tes[grepl('PWK', tes$V2), ]





get_clean_readCount <- function(x){
  
  sn = basename(dirname(x))
  tmp <- read.table(x) %>% as_tibble()
  tmp$gene_name <- gsub('_[PC].*$', '', tmp$V2)
  
  tmp_c57 <- tmp[grepl('C57BL', tmp$V2), ]
  
  colnames(tmp_c57) <- c(paste0(sn, '_C57'), 'gr_c57', 'gene_name')
  tmp_c57 <- tmp_c57[, c(1, 3)]
  
  
  tmp_pwk <- tmp[grepl('PWK_PhJ', tmp$V2), ]
  colnames(tmp_pwk) <- c(paste0(sn, '_PWK'), 'gr_pwk', 'gene_name')
  tmp_pwk <- tmp_pwk[, c(1, 3)]
  
  clean_tibble <- tibble(gene_name = unique(tmp$gene_name))
  
  clean_tibble <- left_join(clean_tibble, tmp_c57) %>% left_join(tmp_pwk)
  
  #clean_tibble[is.na(clean_tibble)] <- 0
  return(clean_tibble)
}


get_clean_readCount(stat_files[5])


merged_readCount <- lapply(stat_files, get_clean_readCount)


names(merged_readCount) <- basename(dirname(stat_files))




gene_meta <- read_tsv('~/cluster_home/ref/GENCODE/mm39_vM33/fetched_info/genes_gencode_clean.txt')

gene_meta %<>% filter(seqname == 'chrX', gene_type %in% c('lncRNA', 'protein_coding'))


final_stat <- tibble(gene_name = gene_meta$gene_name)


table(merged_readCount$sample_1_F1_F_6W_CCl4_1_2$gene_name %in% final_stat$gene_name)


final_stat <- left_join(final_stat, merged_readCount$sample_1_F1_F_6W_CCl4_1) %>%
  left_join(merged_readCount$sample_1_F1_F_6W_CCl4_1_2) %>%
  left_join(merged_readCount$sample_2_F1_F_6W_CCl4_1) %>%
  left_join(merged_readCount$sample_2_F1_F_6W_CCl4_1_2) %>%
  left_join(merged_readCount$sample_2_F1_F_6W_Con_1) %>%
  left_join(merged_readCount$sample_2_F1_F_6W_Con_1_2) %>%
  left_join(merged_readCount$sample_2_F1_F_6W_Con_2) %>%
  left_join(merged_readCount$sample_2_F1_F_6W_Con_2_2) %>%
  left_join(merged_readCount$sample_2_F1_M_6W_CCl4_1) %>%
  left_join(merged_readCount$sample_2_F1_M_6W_CCl4_2) %>%
  left_join(merged_readCount$sample_2_F1_M_6W_CCl4_3) %>%
  left_join(merged_readCount$sample_2_F1_M_6W_CCl4_4) %>%
  left_join(merged_readCount$sample_2_F1_M_6W_Con_1) %>%
  left_join(merged_readCount$sample_2_F1_M_6W_Con_2) %>%
  left_join(merged_readCount$sample_2_F1_M_6W_Con_3) %>%
  left_join(merged_readCount$sample_4_F1_F_6W_CCl4_1) %>%
  left_join(merged_readCount$sample_4_F1_F_6W_CCl4_2) %>%
  left_join(merged_readCount$sample_4_F1_F_6W_CCl4_3) %>%
  left_join(merged_readCount$sample_4_F1_F_6W_CCl4_4) %>%
  left_join(merged_readCount$sample_4_F1_F_6W_CCl4_5) %>%
  left_join(merged_readCount$sample_4_F1_M_6W_CCl4_1) %>%
  left_join(merged_readCount$sample_4_F1_M_6W_CCl4_2) %>%
  left_join(merged_readCount$sample_4_F1_M_6W_Con_1)  %>%  
  left_join(merged_readCount$sample_5_F1_M_6W_Con_1)   


final_stat[is.na(final_stat)] <- 0


final_stat <- final_stat[apply(final_stat[, 2:49], 1, sum) > 10, ]



write_csv(final_stat, '~/cluster_home/project/liverCancer/scripts/mouse_F1/RNA_seq/data/f1_mice_haplotype_readCounts_rmdup.csv')


pheatmap::pheatmap(log(final_stat[, 2:49]+ 0.1))


colnames(final_stat)


final_stat_select <- final_stat[, c('gene_name', 
                                    'sample_2_F1_F_6W_Con_1_C57', "sample_2_F1_F_6W_Con_1_PWK",
                                    "sample_2_F1_F_6W_Con_1_2_C57", "sample_2_F1_F_6W_Con_1_2_PWK",
                                    "sample_2_F1_F_6W_CCl4_1_C57", "sample_2_F1_F_6W_CCl4_1_PWK",
                                    "sample_4_F1_F_6W_CCl4_4_C57", "sample_4_F1_F_6W_CCl4_4_PWK" ,
                                    "sample_4_F1_F_6W_CCl4_5_C57", "sample_4_F1_F_6W_CCl4_5_PWK", 
                                    "sample_2_F1_M_6W_Con_3_C57", 'sample_4_F1_M_6W_Con_1_C57',
                                    "sample_2_F1_M_6W_CCl4_3_C57", "sample_4_F1_M_6W_CCl4_1_C57")]


colnames(final_stat)
#2-F1-F-6W-Con-1_clean_1.fq.gz	22809760
#2-F1-F-6W-Con-1-2_clean_1.fq.gz	20690757
#2-F1-F-6W-CCl4-1_clean_1.fq.gz	22453980
#4-F1-F-6W-CCl4-4_clean__clean_1.fq.gz	31105286
#4-F1-F-6W-CCl4-5_clean__clean_1.fq.gz	29250053
#
#2-F1-M-6W-Con-3_clean__clean_1.fq.gz	23601182
#4-F1-M-6W-Con-1_clean__clean_1.fq.gz	19193999
#2-F1-M-6W-CCl4-3_clean__clean_1.fq.gz	28849071
#4-F1-F-6W-CCl4-1_clean__clean_1.fq.gz	23365944


final_stat_select$sample_2_F1_F_6W_Con_1_C57 <- final_stat_select$sample_2_F1_F_6W_Con_1_C57 / 1.1
final_stat_select$sample_2_F1_F_6W_Con_1_PWK <- final_stat_select$sample_2_F1_F_6W_Con_1_PWK / 1.1
final_stat_select$sample_2_F1_F_6W_Con_1_2_C57 <- final_stat_select$sample_2_F1_F_6W_Con_1_2_C57 /1
final_stat_select$sample_2_F1_F_6W_Con_1_2_PWK <- final_stat_select$sample_2_F1_F_6W_Con_1_2_PWK /1
final_stat_select$sample_2_F1_F_6W_CCl4_1_C57  <- final_stat_select$sample_2_F1_F_6W_CCl4_1_C57 /1
final_stat_select$sample_2_F1_F_6W_CCl4_1_PWK  <- final_stat_select$sample_2_F1_F_6W_CCl4_1_PWK /1
final_stat_select$sample_4_F1_F_6W_CCl4_4_C57  <- final_stat_select$sample_4_F1_F_6W_CCl4_4_C57 /1.08
final_stat_select$sample_4_F1_F_6W_CCl4_4_PWK  <- final_stat_select$sample_4_F1_F_6W_CCl4_4_PWK /1.08
final_stat_select$sample_4_F1_F_6W_CCl4_5_C57  <- final_stat_select$sample_4_F1_F_6W_CCl4_5_C57 /1.4
final_stat_select$sample_4_F1_F_6W_CCl4_5_PWK  <- final_stat_select$sample_4_F1_F_6W_CCl4_5_PWK /1.4



final_stat_select$sample_2_F1_M_6W_Con_3_C57 <- final_stat_select$sample_2_F1_M_6W_Con_3_C57/1.23
final_stat_select$sample_2_F1_M_6W_CCl4_3_C57  <- final_stat_select$sample_2_F1_M_6W_CCl4_3_C57 / 1.5
final_stat_select$sample_4_F1_M_6W_CCl4_1_C57 <- final_stat_select$sample_4_F1_M_6W_CCl4_1_C57/1.23



final_stat_select[, 2:15] <- round(final_stat_select[, 2:15], digits = 1)

final_stat_select <- final_stat_select[apply(final_stat_select[, 2:15], 1, sum) > 10, ]

pheatmap::pheatmap(log(final_stat_select[, 2:15]+ 0.1))




# CCL4 VS CONTROL  
female_fc <- (((final_stat_select$sample_2_F1_F_6W_CCl4_1_PWK +
                    final_stat_select$sample_4_F1_F_6W_CCl4_4_PWK +
                    final_stat_select$sample_4_F1_F_6W_CCl4_5_PWK) / 3) +5 )/
             ((final_stat_select$sample_2_F1_F_6W_Con_1_PWK +
                   final_stat_select$sample_2_F1_F_6W_Con_1_2_PWK)/2 +5)%>% log2()

female_fc <- (final_stat_select$sample_2_F1_F_6W_CCl4_1_PWK +
                final_stat_select$sample_4_F1_F_6W_CCl4_4_C57 +
                final_stat_select$sample_4_F1_F_6W_CCl4_5_PWK) /
  (final_stat_select$sample_2_F1_F_6W_Con_1_PWK +
     final_stat_select$sample_2_F1_F_6W_Con_1_2_PWK) %>% log2()





male_fc <- ((final_stat_select$sample_2_F1_M_6W_CCl4_3_C57 +
                final_stat_select$sample_4_F1_M_6W_CCl4_1_C57 ) / 2 + 5) / 
  ((final_stat_select$sample_2_F1_M_6W_Con_3_C57 +
     final_stat_select$sample_4_F1_M_6W_Con_1_C57) /2 + 5 ) %>% log2()

t.test(female_fc, male_fc, paired = T)



boxplot(list(female_xa = female_fc, male_xa = male_fc), ylim = c(0, 30),
        ylab = 'log2( (CCL4/CONTROL) readcount )', outline =F, las =2)


write_csv(female_fc %>% as_tibble(), '~/cluster_home/project/liverCancer/scripts/figures_update/fig3/data/female_fc.csv')

write_csv(male_fc %>% as_tibble(), '~/cluster_home/project/liverCancer/scripts/figures_update/fig3/data/male_fc.csv')



# Female Xa vs female Xi 

f_xa <- log((final_stat_select$sample_2_F1_F_6W_Con_1_PWK + final_stat_select$sample_2_F1_F_6W_Con_1_2_PWK)/2 + 5)

f_xi <- log((final_stat_select$sample_2_F1_F_6W_Con_1_C57 + final_stat_select$sample_2_F1_F_6W_Con_1_2_C57)/2 + 5)


boxplot(list(f_xa, f_xi))

#
final_Xa <- final_stat_select[(final_stat_select$sample_2_F1_F_6W_Con_1_PWK + final_stat_select$sample_2_F1_F_6W_Con_1_2_PWK)/2 >
                    (final_stat_select$sample_2_F1_F_6W_Con_1_C57 + 
                       final_stat_select$sample_2_F1_F_6W_Con_1_2_C57)/2,   ]

f_xa <- log2((final_Xa$sample_2_F1_F_6W_Con_1_PWK + final_Xa$sample_2_F1_F_6W_Con_1_2_PWK)/2 )

f_xi <- log2((final_Xa$sample_2_F1_F_6W_Con_1_C57 + final_Xa$sample_2_F1_F_6W_Con_1_2_C57)/2 )

boxplot(list( xi = f_xi, xa = f_xa), ylab = 'log2(normalized readcount)')


f_xa <- (final_Xa$sample_2_F1_F_6W_Con_1_PWK + final_Xa$sample_2_F1_F_6W_Con_1_2_PWK)/2 

f_xi <- (final_Xa$sample_2_F1_F_6W_Con_1_C57 + final_Xa$sample_2_F1_F_6W_Con_1_2_C57)/2

boxplot(list( xi = f_xi, xa = f_xa), ylab = 'normalized readcount', ylim = c(0, 100), outline =F)









# selected genes:


final_stat <- read_csv('~/cluster_home/project/liverCancer/scripts/mouse_F1/RNA_seq/data/f1_mice_haplotype_readCounts_rmdup.csv')



final_stat_select <- final_stat[, c('gene_name', 
                                    'sample_2_F1_F_6W_Con_1_C57', "sample_2_F1_F_6W_Con_1_PWK",
                                    "sample_2_F1_F_6W_Con_1_2_C57", "sample_2_F1_F_6W_Con_1_2_PWK",
                                    "sample_2_F1_F_6W_CCl4_1_C57", "sample_2_F1_F_6W_CCl4_1_PWK",
                                    "sample_4_F1_F_6W_CCl4_4_C57", "sample_4_F1_F_6W_CCl4_4_PWK" ,
                                    "sample_4_F1_F_6W_CCl4_5_C57", "sample_4_F1_F_6W_CCl4_5_PWK", 
                                    "sample_2_F1_M_6W_Con_3_C57", 'sample_4_F1_M_6W_Con_1_C57',
                                    "sample_2_F1_M_6W_CCl4_3_C57", "sample_4_F1_M_6W_CCl4_1_C57")]


colnames(final_stat_select)



final_stat_select$f_pwk_vs_c57 <- (final_stat_select$sample_2_F1_F_6W_Con_1_PWK +1) / (final_stat_select$sample_2_F1_F_6W_Con_1_C57 +1)


final_stat_select <- arrange(final_stat_select, desc(f_pwk_vs_c57))



final_stat_select <- final_stat_select[, c('gene_name', 
                                    'sample_2_F1_F_6W_Con_1_C57', "sample_2_F1_F_6W_Con_1_PWK",
                                    "sample_2_F1_F_6W_CCl4_1_C57", "sample_2_F1_F_6W_CCl4_1_PWK",
                                    "sample_4_F1_F_6W_CCl4_4_C57", "sample_4_F1_F_6W_CCl4_4_PWK" ,
                                
                                    "sample_2_F1_M_6W_Con_3_C57", 'sample_4_F1_M_6W_Con_1_C57',
                                    "sample_2_F1_M_6W_CCl4_3_C57", "sample_4_F1_M_6W_CCl4_1_C57")]


write_csv(final_stat_select, '~/cluster_home/project/liverCancer/scripts/mouse_F1/RNA_seq/data/f1_mice_haplotype_readCounts_rmdup_example.csv')


































































































































































